---
apiVersion: v1      # the apiVersion to use
kind: Pod           # example Pod / Deployment
metadata:
  name: api-svc         # name to apply
  labels:
    name:  api      # label name
spec:
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "php.local"
    - "py.local"
  - ip: "10.1.2.3"
    hostnames:
    - "php.remote"
    - "py.remote"      
  containers:
  -
    name:  php      # name of container
    image: reg.alta3.com/3245-gottreu-php-api      # image to use if no URL provided hub.docker.com is used
    ports:
     -
       name: http     # port name
       containerPort: 80     # access on this port (int)
       protocol:  TCP         # TCP or UDP
  -
    name:  python      # name of container
    image:  reg.alta3.com/3245-gottreu-python-api      # image to use if no URL provided hub.docker.com is used
    ports:
     -
       name: http     # port name
       containerPort: 5000     # access on this port (int)
       protocol:  TCP         # TCP or UDP
